# Generated by Django 6.0.6 on 2026-07-19 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_alter_board_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ستون',
                'verbose_name_plural': 'ستون\u200cها',
                'ordering': ('position', 'pk'),
                'indexes': [models.Index(fields=['board', 'is_archived', 'position'], name='columns_board_state_pos_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('board', 'position'), name='columns_active_board_pos_unique')],
            },
        ),
    ]
