# Generated by Django 6.0.6 on 2026-07-20 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("columns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("medium", "متوسط"),
                            ("high", "زیاد"),
                            ("urgent", "فوری"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "برای انجام"),
                            ("in_progress", "درحال انجام"),
                            ("blocked", "مسدود"),
                            ("done", "انجام\u200cشده"),
                            ("canceled", "لغوشده"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="columns.column",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "وظیفه",
                "verbose_name_plural": "وظایف",
                "ordering": ["position", "pk"],
                "indexes": [
                    models.Index(
                        fields=["column", "is_archived", "position"],
                        name="tasks_column_state_pos_idx",
                    ),
                    models.Index(
                        fields=["assignee", "status", "due_at"],
                        name="tasks_assignee_status_due_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_archived", False)),
                        fields=("column", "position"),
                        name="tasks_active_column_pos_unique",
                    )
                ],
            },
        ),
    ]
