# Generated by Django 6.0.6 on 2026-07-22 15:45

from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


def backfill_archived_at(
    apps,
    schema_editor,
):
    Task = apps.get_model(
        "tasks",
        "Task",
    )

    Task.objects.filter(
        is_archived=True,
        archived_at__isnull=True,
    ).update(
        archived_at=F("updated_at"),
    )


def clear_archived_at(
    apps,
    schema_editor,
):
    Task = apps.get_model(
        "tasks",
        "Task",
    )

    Task.objects.update(
        archived_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("columns", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_archived_at,
            clear_archived_at,
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=(
                    Q(
                        is_archived=False,
                        archived_at__isnull=True,
                    )
                    | Q(
                        is_archived=True,
                        archived_at__isnull=False,
                    )
                ),
                name=(
                    "tasks_archive_state_consistent"
                ),
            ),
        ),
    ]