# Generated by Django 6.0.6 on 2026-07-29 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_archived_at_task_tasks_archive_state_consistent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Task ساخته شد'), ('updated', 'Task ویرایش شد'), ('status_changed', 'وضعیت تغییر کرد'), ('assignee_changed', 'مسئول تغییر کرد'), ('moved', 'به ستون دیگری منتقل شد'), ('reordered', 'جایگاه تغییر کرد'), ('commented', 'دیدگاه ثبت شد'), ('comment_updated', 'دیدگاه ویرایش شد'), ('comment_deleted', 'دیدگاه حذف شد'), ('archived', 'Task آرشیو شد'), ('restored', 'Task بازیابی شد')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
            ],
            options={
                'verbose_name': 'فعالیت Task',
                'verbose_name_plural': 'فعالیت\u200cهای Task',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='tasks_activity_task_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=3000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_task_ccomments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'دیدگاه Task',
                'verbose_name_plural': 'دیدگاه\u200cهای Task',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['task', 'is_deleted', 'created_at'], name='task_comment_task_state_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('deleted_by__isnull', True), ('is_deleted', False)), models.Q(('deleted_at__isnull', False), ('is_deleted', True)), _connector='OR'), name='task_comment_deleted_consistent')],
            },
        ),
    ]
