# Generated by Django 6.0.6 on 2026-07-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-updated_at', '-pk'), 'verbose_name': 'برد', 'verbose_name_plural': 'بردها'},
        ),
    ]
