from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path(
        'archived/',
        views.ArchivedTaskListView.as_view(),
        name='archived_list',
    ),
    path(
        'create/',
        views.TaskCreateView.as_view(),
        name="create",
    ),
    path(
        '<int:task_pk>/',
        views.TaskDetailView.as_view(),
        name='detail',
    ),
    path(
        (
            "<int:task_pk>/"
            "comments/create/"
        ),
        (
            views
            .TaskCommentCreateView
            .as_view()
        ),
        name="comment_create",
    ),
    path(
        (
            "<int:task_pk>/"
            "comments/"
            "<int:comment_pk>/"
            "update/"
        ),
        (
            views
            .TaskCommentUpdateView
            .as_view()
        ),
        name="comment_update",
    ),
    path(
        (
            "<int:task_pk>/"
            "comments/"
            "<int:comment_pk>/"
            "delete/"
        ),
        (
            views
            .TaskCommentDeleteView
            .as_view()
        ),
        name="comment_delete",
    ),
    path(
        '<int:task_pk>/update/',
        views.TaskUpdateView.as_view(),
        name='update',
    ),
    path(
        '<int:task_pk>/status/',
        views.TaskStatusUpdateView.as_view(),
        name='status',
    ),
    path(
        '<int:task_pk>/move/',
        views.TaskMoveView.as_view(),
        name='move',
    ),
    path(
        "<int:task_pk>/reorder/",
        views.TaskReorderView.as_view(),
        name='reorder',
    ),
    path(
        "<int:task_pk>/drag-reorder/",
        (
            views
            .TaskDragReorderView
            .as_view()
        ),
        name="drag_reorder",
    ),
    path(
        "<int:task_pk>/move-up/",
        views.TaskMoveUpView.as_view(),
        name='move_up',
    ),
    path(
        "<int:task_pk>/move-down/",
        views.TaskMoveDownView.as_view(),
        name='move_down',
    ),
    path(
        '<int:task_pk>/archive/',
        views.TaskArchiveView.as_view(),
        name='archive',
    ),
    path(
        '<int:task_pk>/restore/',
        views.TaskRestoreView.as_view(),
        name='restore',
    ),
    path(
        '<int:task_pk>/delete/',
        views.TaskDeleteView.as_view(),
        name='delete',
    ),
]
