# Generated by Django 6.0.6 on 2026-08-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "واگذاری Task"),
                            ("task_reassigned", "تغییر مسئول Task"),
                            ("task_status_changed", "تغییر وضعیت Task"),
                            ("task_commented", "دیدگاه جدید Task"),
                            ("workspace_invited", "دعوت به Workspace"),
                            ("workspace_role_changed", "تغییر نقش Workspace"),
                            ("workspace_removed", "حذف از Workspace"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "target_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notif_rec_read_created_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type", "-created_at"],
                        name="notif_rec_type_created_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_read", False), ("read_at__isnull", True)),
                            models.Q(("is_read", True), ("read_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="notification_read_state_consistent",
                    )
                ],
            },
        ),
    ]
